ItemEvents.tooltip(event => {
    event.add('minecraft:clay_ball', '§6Obtained by crushing dirt on crushing tub')
    event.add('minecraft:campfire', '§6Item form require silk touch')
    event.add('reactive:scroll', '§6Right click a cauldron to convert into a crucible')
    event.add('minecraft:bone_meal', '§6Obtained by compost stuff on composter')
    event.add('minecraft:string', '§6Obtained by flax plants')
    event.add('bluepower:engine', '§1Volts §finto §cRF/FE')
    event.add('bluepower:solar_panel', 'Generate §1Volts')
	event.add('bluepower:blulectric_alloyfurnace', 'Burn §1Volts §fto alloy')
	event.add('bluepower:blulectric_furnace', 'Burn §1Volts §fto cook')
    event.add('homespun:redstone_acid', 'Deoxide §6copper blocks §fand convert §8cobblestone §finto §7gravel')
    event.add('homespun:ironwood_leaves', 'Can drop §5berries')
    event.add('ae2:facade', '§6You can craft using any solid block with around 4 cable anchor')
    event.add('homespun:ironberry_juice_bottle', 'Click with a bottle on a tank of §7iron berry §fto fill up')
    event.add('#ironberry:crushing_output', '§6Obtained by crushing berries on crushing tub or on a squeezer')
    event.add('#ironberry:bluealloy', '§6Can be automated by import and export items up and down side')
    event.add('kubejs:instability', '§aA cube of water and lava, what can go wrong?')
    event.add('#ironberry:rate_32', '§fCan Transfer §a32 §fChannels')
    event.add('#ironberry:rate_8', '§fCan Transfer §a8 §fChannels')
    event.add('#ironberry:onlyforge_energy', '§cNo Channel Required!')
	event.add('ae2:controller','§fFree §a32 §fChannels for each face')
	event.add('#ironberry:cpu','§a1 §fChannel for each CPU with minimal §a1 §fcrafting storage')
	event.add('#ironberry:req_1','§a1 §fChannel Required')
	event.add('#ae2:memory_cards','Best friend of §aP2P §fEngineers')
	event.add('#ironberry:blue_slabs','§6Multiblock parts')
	event.add('ironchest:copper_chest','§645 Slots')
	event.add('ironchest:iron_chest','§654 Slots')
	event.add('ironchest:gold_chest','§681 Slots')
	event.add('ironchest:diamond_chest','§6108 Slots')
	event.add('pneumaticcraft:smart_chest','§672 Slots with upgrades')
	event.add('pneumaticcraft:reinforced_chest','§636 Slots')
	event.add('#ironberry:ae2_chests','§636 Slots')
	event.add('tombstone:decorative_subaraki_grave','§6Subaraki confirmed')
	event.add('minecraft:honeycomb','You can use a §6Hive Hopper §fto obtain §6honeycomb §fand §6honey §ffull automatic')
	event.add('thermal:device_hive_extractor','Extract §6honeycomb §fand §6honey §ffrom §6honey hives §fand §6bee hives')
	event.add('minecraft:lily_pad','You can obtain by placing water around a Growing Standing Stone')
})
