[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 762726289341677668
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Game Starting..."
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% still on Main Menu"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently on Sky"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = "IronBerry Expert"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://github.com/DevDyna/CurseFiles/blob/main/curse/ironberry/rpc/logo.gif?raw=true"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "IronBerry Expert"
		url = "https://www.curseforge.com/minecraft/modpacks/ironberry-expert"

[custom]
	#Must these variables be parsed along with other variables
	enabled = false
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = false
	dimensions = []

