name: Bug Report
description: Have you find a bug ? Squash it!
title: "[Bug]: "
labels: [bug, need support]
assignees: DevDyna
body:
  - type: checkboxes
    id: new-issue
    attributes:
      label: Core
      description: Biip Boop , Something happen !
      options:
        - label: I have searched for this issue on this repository
          required: true
        - label: This bug persist and I need help
          required: true
          
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Blup Blup , We are on deep !
      options:
        - Singleplayer/Local | NO LAN
        - Multiplayer        | LAN
        - Multiplayer        | Dedicated server
    validations:
      required: true
        
  - type: input
    id: version
    attributes:
      label: Modpack Version
      placeholder: ex. 0.7c
      description: Insert a valid version !
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happen
      placeholder: Describe what you are doing
    validations:
      required: true
      
      
  - type: textarea
    id: procedure
    attributes:
      label: Procedure
      description: Describe layer by layer what you have done (please not from prehistory to now , only basics..)
      placeholder: Describe here!
    validations:
      required: true
