blank_issues_enabled: false
contact_links:
  - name: Missing/Broken Recipe Issues
    url: https://github.com/DevDyna/IronBerry/discussions/27
    about: Write a comment on this discussion like a issue
