name: New Feature
description: All good ideas can be usefull !
labels: [enhancement, need support]
assignees: DevDyna
body:
  - type: checkboxes
    id: new-issue
    attributes:
      label: Core Section
      description: Biip Boop , Something happen !
      options:
        - label: I have searched for this issue on this repository
          required: true
        - label: I like what you are doing
          required: true
          

  - type: markdown
    attributes:
      value: Case Section

  - type: dropdown
    id: stage
    attributes:
      label: Stage Selection
      options:
        - <Empty>
        - Introduction
        - Campain 1
        - Campain 2
        - Campain 3
        - Campain 4
    validations:
      required: false

  - type: dropdown
    id: stage
    attributes:
      label: MOD Selection
      options:
        - <Empty>
        - Add / Include
        - Modify
        - Remove / Exclude
    validations:
      required: false

  - type: dropdown
    id: stage
    attributes:
      label: QUEST Selection
      options:
        - <Empty>
        - Add / Include
        - Modify
        - Remove / Exclude
    validations:
      required: false

  - type: dropdown
    id: stage
    attributes:
      label: RECIPES / EVENTS Selection
      options:
        - <Empty>
        - Add / Include
        - Modify
        - Remove / Exclude
    validations:
      required: false

  - type: checkboxes
    id: case
    attributes:
      label: Various Selection
      description: What is your case?
      options:
        - label: Enable a disabled item with X scope











        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe it
      placeholder: 1 / sqrt(i) = 0,707106781 - 0,707106781 i
    validations:
      required: true
      
      
  - type: input
    id: missing-case
    attributes:
      label: Missing Your Case ?
      description: Write he what case you have find that still missing on case section
      placeholder: Hey can you add *lollypop* because can be overpowered ??? [NO]
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Additional things
      description: Anything else , included videos , gifs , screenshots and more..
      placeholder: ln x- ln y
    validations:
      required: true
