ServerEvents.tags('item', event => {
//
//devices
//
event.add('thermal:devices','#thermal:ducts')
event.add('thermal:devices','thermal:device_potion_diffuser')
event.add('thermal:devices','thermal:device_fisher')
event.add('thermal:devices','thermal:device_soil_infuser')
event.add('thermal:devices','thermal:device_composter')
event.add('thermal:devices','thermal:device_hive_extractor')
event.add('thermal:devices','thermal:device_tree_extractor')
event.add('thermal:devices','thermal:device_nullifier')
event.add('thermal:devices','thermal:device_water_gen')
event.add('thermal:devices','thermal:device_collector')
event.add('thermal:devices','thermal:device_rock_gen')
event.add('thermal:devices','thermal:charge_bench')
event.add('thermal:devices','thermal:tinker_bench')
event.add('thermal:devices','thermal:item_buffer')
event.add('thermal:devices','bluepower:block_breaker')
event.add('thermal:devices','bluepower:igniter')
event.add('thermal:devices','bluepower:buffer')
event.add('thermal:devices','bluepower:deployer')
event.add('thermal:devices','bluepower:transposer')
event.add('thermal:devices','bluepower:ejector')
event.add('thermal:devices','bluepower:engine')
event.add('thermal:devices','prettypipes:item_terminal')
event.add('thermal:devices','prettypipes:pressurizer')
//
//servos
//
event.add('thermal:servo','thermal:energy_limiter_attachment')
event.add('thermal:servo','thermal:turbo_servo_attachment')
event.add('thermal:servo','thermal:filter_attachment')
event.add('thermal:servo','thermal:servo_attachment')
})